import { type NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Page List</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="text-2xl text-center text-white border-2 border-gray-400 rounded-lg bg-gray-500 m-40 mb-4">
        <h1 className="m-6">Lista de compras</h1>
        </div>
        <div className="flex mr-40">
        <input type="text" className="text-lg text-gray-400 border-2 border-gray-400 rounded-lg hover:bg-gray-200 ml-40 w-80"/>
        <input type="text" className="text-lg text-gray-400 border-2 border-gray-400 rounded-lg hover:bg-gray-200 ml-8 w-80"/>
        <div className="text-center border-2 border-gray-400 rounded-2xl bg-green-500 hover:bg-green-200 w-fit ml-10">
        <h1 className="m-6">ADD</h1>
        </div>
        <div className="text-center border-2 border-gray-400 rounded-2xl bg-red-500 hover:bg-red-200 w-fit ml-2">
        <h1 className="m-6">DEL</h1>
        </div>
        </div>
      </main>
    </>
  );
};

export default Home;